[project]
name = "mazegen"
version = "1.0.0"
description = "a Maze Generator with three different algorithms"
authors = [
    {name = "Abdelfatah Laktaoui",email = "abdalfattahlaktaoui98@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "pydantic (>=2.12.5,<3.0.0)"
]

[project.optional-dependencies]
dev = [
    "mypy>=1.0.0",
    "pytest>=7.0.0",
    "flake8>=6.0.0",
    "pydantic>=2.12.5",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
